server:
  port: 8085
spring:
  application:
    name: erp-list-promotion-service
  datasource:
    url: jdbc:mysql://39.105.104.224:3306/erp_list_promotion?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      server-addr: 39.105.104.224:8848
mybatis-plus:
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.erplist: debug
  file:
    path: "logs/${spring.application.name}"

