server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        # 管理后台接口（用户服务）
        - id: admin-service
          uri: lb://erp-list-user-service
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
        # 用户服务
        - id: user-service
          uri: lb://erp-list-user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        # 权限接口（用户服务）
        - id: permission-service
          uri: lb://erp-list-user-service
          predicates:
            - Path=/api/permissions
          filters:
            - StripPrefix=1
        # 店铺服务
        - id: seller-service
          uri: lb://erp-list-seller-service
          predicates:
            - Path=/api/sellers/**
          filters:
            - StripPrefix=1
        # 订单服务
        - id: order-service
          uri: lb://erp-list-order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        # 商品服务
        - id: product-service
          uri: lb://erp-list-product-service
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
        # 采购服务
        - id: purchase-service
          uri: lb://erp-list-purchase-service
          predicates:
            - Path=/api/purchases/**
          filters:
            - StripPrefix=1
        # 退款服务
        - id: refund-service
          uri: lb://erp-list-refund-service
          predicates:
            - Path=/api/refunds/**
          filters:
            - StripPrefix=1
        # 补货服务
        - id: replenishment-service
          uri: lb://erp-list-replenishment-service
          predicates:
            - Path=/api/replenishments/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true


